/* Lenguaje de consultas --> Structure Language Query --> Base de datos relacionales!
--> Creado en los 70s
--> Sirve para gestionar bases de datos relacionales
--> Es un standar, las primeras bases de datos eran basadas en ficheros
--> Era muy complejo relacionar esos datos antes de SQL
--> SQL es un lenguaje declarativo, no es necesario decirle a la base de datos como hacer las cosas, solo que queremos hacer
--> Esta regulado por normas ISO y normas AnCI
--> Una base de datos es un sistema que permite almacenar y gestionar datos, en muchos casos son bases de datos relacionales, es decir se pueden relacionar unos datos con otros
--> Las bases de datos sirven ser eje entre sistemas multidispositivos --> Netflix como APPTV usa la misma data que la app IOS
--> SQL funciona con tablas es decir guardaran los datos de usuarios, likes, amigos etc... el hecho es que SQL es capaz de relacionar estas tab las para crear informacion detallada de usuarios
--> Este lenguaje nor permite crear queries, es decir operaciones y condicionales sobre informacion
--> DBMS --> Database Managment System --> Motor de base de datos que nos permiten tener cierta estabilidad y seguridad
--> MySQL, SQL Server, Oracle, PostgreSQL, SQLite, MariaDB, etc...